version: '3'
services:
  influxdb:
    image: influxdb:1.3-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8083"
      - "8086"
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:1.3-alpine
    depends_on:
      - influxdb
    ports:
      - "8888:8888"
    expose:
      - "8888"
    volumes:
      - ./data/chronograf:/var/lib/chronograf

  grafana:
    image: "grafana/grafana"
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
